services:
  surveil:
    build: .
    image: surveil:latest
    stdin_open: true
    tty: true
    volumes:
      - surveil-data:/data
    entrypoint: ["surveil"]
    command: ["--help"]

volumes:
  surveil-data:
